
package com.example.sparkml;

import org.apache.spark.sql.SparkSession;
import org.apache.spark.ml.feature.VectorAssembler;
import org.apache.spark.ml.regression.LinearRegression;
import org.apache.spark.ml.regression.LinearRegressionModel;
import org.apache.spark.ml.evaluation.RegressionEvaluator;
import org.apache.spark.sql.Dataset;
import org.apache.spark.sql.Row;
import java.util.Arrays;
import java.util.List;

public class SparkMLlibExample {

    public static void main(String[] args) {
        // 1. Initialize Spark Session
        SparkSession spark = SparkSession.builder()
                .appName("SparkMLlibLinearRegression")
                .master("local[*]") // Use local mode for demonstration
                .getOrCreate();

        System.out.println("Spark Session initialized successfully.");

        // 2. Prepare Sample Data
        // In a real-world scenario, data would be loaded from HDFS, S3, etc.
        List<LabeledPoint> data = Arrays.asList(
                new LabeledPoint(1.0, 2.0, 3.0, 4.0),
                new LabeledPoint(2.0, 3.0, 4.0, 5.0),
                new LabeledPoint(3.0, 4.0, 5.0, 6.0),
                new LabeledPoint(4.0, 5.0, 6.0, 7.0),
                new LabeledPoint(5.0, 6.0, 7.0, 8.0),
                new LabeledPoint(6.0, 7.0, 8.0, 9.0),
                new LabeledPoint(7.0, 8.0, 9.0, 10.0),
                new LabeledPoint(8.0, 9.0, 10.0, 11.0),
                new LabeledPoint(9.0, 10.0, 11.0, 12.0),
                new LabeledPoint(10.0, 11.0, 12.0, 13.0)
        );

        Dataset<Row> df = spark.createDataFrame(data, LabeledPoint.class);
        System.out.println("Sample data created:");
        df.show();

        // 3. Assemble Features
        // VectorAssembler is a transformer that combines a given list of columns
        // into a single vector column. It is useful for combining raw features
        // and features generated by different feature transformers into a single
        // feature vector, to train ML models like Linear Regression.
        VectorAssembler assembler = new VectorAssembler()
                .setInputCols(new String[]{"feature1", "feature2", "feature3"})
                .setOutputCol("features");

        Dataset<Row> trainingData = assembler.transform(df).select("features", "label");
        System.out.println("Features assembled:");
        trainingData.show();

        // 4. Train a Linear Regression Model
        // LinearRegression is an estimator that trains a linear regression model.
        // It takes parameters like regularization, elastic net mixing, etc.
        LinearRegression lr = new LinearRegression()
                .setFeaturesCol("features")
                .setLabelCol("label")
                .setMaxIter(10)
                .setRegParam(0.3)
                .setElasticNetParam(0.8);

        System.out.println("Training Linear Regression model...");
        LinearRegressionModel lrModel = lr.fit(trainingData);
        System.out.println("Model training complete.");

        // 5. Print the coefficients and intercept for linear regression
        System.out.println("Coefficients: " + lrModel.coefficients() + " Intercept: " + lrModel.intercept());

        // 6. Make predictions on the training data
        Dataset<Row> predictions = lrModel.transform(trainingData);
        System.out.println("Predictions on training data:");
        predictions.select("label", "prediction", "features").show();

        // 7. Evaluate the model
        RegressionEvaluator evaluator = new RegressionEvaluator()
                .setLabelCol("label")
                .setPredictionCol("prediction")
                .setMetricName("rmse"); // Root Mean Squared Error

        double rmse = evaluator.evaluate(predictions);
        System.out.println("Root Mean Squared Error (RMSE) on training data = " + rmse);

        // 8. Stop Spark Session
        spark.stop();
        System.out.println("Spark Session stopped.");
    }

    // Helper class for creating LabeledPoint objects
    public static class LabeledPoint implements java.io.Serializable {
        private double label;
        private double feature1;
        private double feature2;
        private double feature3;

        public LabeledPoint(double label, double feature1, double feature2, double feature3) {
            this.label = label;
            this.feature1 = feature1;
            this.feature2 = feature2;
            this.feature3 = feature3;
        }

        public double getLabel() {
            return label;
        }

        public void setLabel(double label) {
            this.label = label;
        }

        public double getFeature1() {
            return feature1;
        }

        public void setFeature1(double feature1) {
            this.feature1 = feature1;
        }

        public double getFeature2() {
            return feature2;
        }

        public void setFeature2(double feature2) {
            this.feature2 = feature2;
        }

        public double getFeature3() {
            return feature3;
        }

        public void setFeature3(double feature3) {
            this.feature3 = feature3;
        }
    }
}
